### ISSUE TITLE
Error downloading - no public playlist found

### ISSUE THREAD

**Issue by marlouz** [HoloArchivists/OPENREC-dl#11]
Hi,

I'm not sure if anyone is still working on this tool but I can always try :) As of this month, I suddenly get an error downloading from openrec:

C:\Users\marlo\openrec>python openrec-dl.py -V --username xxx --password xxx https://www.openrec.tv/live/wez9mp0158l
[info:wez9mp0158l] no public playlist found
[playlist:wez9mp0158l] got playlist https://d3cfw2mckicdfw.cloudfront.net/1bce1f2d3ec4c1d19e336e2c77577078298183d630/playlist.m3u8
[playlist:wez9mp0158l] index playlist not identified, please report this at 'https://github.com/HoloArchivists/OPENREC-dl/issues'
[get-m3u8-info] retrieving playlist from https://d3cfw2mckicdfw.cloudfront.net/1bce1f2d3ec4c1d19e336e2c77577078298183d630/playlist.m3u8
[movie:wez9mp0158l] could not find video format 'best'. to view all available formats, use --list-formats

This happens to be a video from a channel I'm subscribed to, I have a valid username and password. The older video's on this channel (1 per month) I have downloaded in the past without problems, if I try to download them again now they raise the same error. Also I've tried to download a free movie from another channel, same error. All movies I've tried to download, I also tried to watch them in my browser (chrome) and that works just fine. 

I hope you're looking for a new Openrec challenge ;) Thanks anyway for the movies I've been able to download with this tool so far!!

**Comment by CetaceanNation** [comment]
Hi, still alive for maintenance. Should be fixed with latest commit [20d5b31](https://github.com/HoloArchivists/OPENREC-dl/commit/20d5b31fd1d90a62dac6b8749a42eedc26afee42), pull that down and let me know if it's working for you as well. Thanks for reporting the issue!

**Comment by marlouz** [comment]
Thank you！
It's giving me an different error now :) First, it said 'NameError: name 'response' is not defined'. I'm a developer, just not familiar with Python (or code to download video's ;)), so I looked in the file and changed 'return response.cookies' to 'return login_response.cookies' (on r653). That fixed the name error, but I don't know if that's causing the next problem: no data in the download. The log says:
C:\Users\marlo\openrec>python openrec-dl.py -V -u xxx -p xxx https://www.openrec.tv/live/wez9mp0158l
[info:wez9mp0158l] no public playlist found
[playlist:wez9mp0158l] got playlist https://d3cfw2mckicdfw.cloudfront.net/1bce1f2d3ec4c1d19e336e2c77577078298183d630/playlist.m3u8
[playlist:wez9mp0158l] index playlist not identified, please report this at 'https://github.com/HoloArchivists/OPENREC-dl/issues'
[get-m3u8-info] retrieving playlist from https://d3cfw2mckicdfw.cloudfront.net/1bce1f2d3ec4c1d19e336e2c77577078298183d630/playlist.m3u8
[movie:wez9mp0158l] writing video to '廣瀬大介のゲーム部屋_4 [wez9mp0158l].ts'
←[?25l
[mpeg-convert] converting video to '廣瀬大介のゲーム部屋_4 [wez9mp0158l].mp4'
←[?25h

So it did 'download' (the title it created is correct, that's the video I'm trying to download), but it's 0 kb... It only took like 1 second to finish. Btw it created the .ts file, not a .mp4. Do you have an idea what's the problem here? Thanks for looking into this, I really appreciate it!

**Comment by CetaceanNation** [comment]
Sorry for the broken update, I overlooked a couple things because I was short on time but I've fixed the issue now. Actually tested with downloading this time too to make sure all responses are fixed.

**Comment by marlouz** [comment]
Hi,

Don't worry about the first fix, it was fun looking into a .py file for once :) And I'm just so glad you've spend your time on this! It's working again now, I was able to download the movie. Thank you!!!!!
