### ISSUE TITLE
could not find video format 'Source'

### ISSUE THREAD

**Issue by praeludiumOrbis** [HoloArchivists/OPENREC-dl#6]
Maybe this happens because it's a 2016 video? I don't know, kinda weird.

```
E:\>openrec-dl.py --cookies openrec.txt --write-info-json --write-thumbnail --write-live-chat https://www.openrec.tv/live/NWfYjanhwgZ
[info:NWfYjanhwgZ] no public playlist found
[info:NWfYjanhwgZ] writing video information to 'osu_ _3 [NWfYjanhwgZ].info.json'
[thumbnail:NWfYjanhwgZ] writing thumbnail to 'osu_ _3 [NWfYjanhwgZ].png'
[live-chat:NWfYjanhwgZ] writing live chat to osu_ _3 [NWfYjanhwgZ].live_chat.json
[movie:NWfYjanhwgZ] could not find video format 'Source'. to view all available formats, use --list-formats

E:\>openrec-dl.py --cookies openrec.txt --write-info-json --write-thumbnail --write-live-chat -F https://www.openrec.tv/live/NWfYjanhwgZ
[info:NWfYjanhwgZ] no public playlist found
[movie:NWfYjanhwgZ] available formats:
NAME    GROUP-ID RESOLUTION FPS  TBR    CODECS
------- -------- ---------- ---- ------ ------------------------
```

**Comment by CetaceanNation** [comment]
Really appreciate you using this and finding these cases. You may very well be right that this is because of it being from 2016, since the hosting is not hidden behind Cloudflare. The playlist file is extremely barebones, far less information than can normally be expected. I'll be able to add support for this.

**Comment by praeludiumOrbis** [comment]
> Really appreciate you using this and finding these cases. 

Really appreciate that you provided this code for free and keep maintaining it! ^^

> the hosting is not hidden behind Cloudflare

wtf? o.O
Can't that more or less be considered a security flaw? Yikes

> The playlist file is extremely barebones, far less information than can normally be expected

Yeahh, makes sense
